name: Build and deploy a container to an Azure Web App

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deply.yml
    with:
      environment: development
      azure-web-app-name: ase-dev-healthflip
      secrets: inherit  