name: Build and deploy a container to an Azure Web App

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy-development:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      azure-web-app-name: ase-dev-healthflip
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  
  deploy-staging:
    name: Deploy
    needs: deploy-development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      azure-web-app-name: ase-stg-healthflip
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  deploy-production:
    name: Deploy
    needs: deploy-staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      azure-web-app-name: ase-prd-healthflip
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}