name: Build and deploy a container to an Azure Web App

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    strategy:
      matrix:
        environment: [development, staging, production]
        azure-web-app-name: [ase-dev-healthflip, ase-stg-healthflip, ase-prd-healthflip]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ matrix.environment }}
      azure-web-app-name: ${{ matrix.azure-web-app-name }}
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}